// Generated by https://quicktype.io

export interface ChatResponse {
    id:      string;
    created: number;
    model:   string;
    object:  string;
    choices: Choice[];
    usage:   Usage;
}

export interface Choice {
    finish_reason: string;
    index:         number;
    message:       Message;
}

export interface Message {
    content: string;
    role:    "assistant";
}

export interface Usage {
    prompt_tokens:     number;
    completion_tokens: number;
    total_tokens:      number;
}
